apiVersion: v1
kind: ServiceAccount
metadata:
  name: qdrant
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.qdrant: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"qdrant"}}'
