apiVersion: v1
kind: Service
metadata:
  labels:
    app: envoy-llama-stack
  name: envoy-llama-stack
  namespace: maas
spec:
  ports:
  - name: web
    port: 8000
    protocol: TCP
  selector:
    app: envoy-llama-stack