apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hcm-ai-advanced-cluster-management
  namespace: openshift-gitops
spec:
  destination:
    name: in-cluster
  project: default
  source:
    path: operators/advanced-cluster-management/operator/overlays/release-2.12
    repoURL: 'https://github.com/app-sre/hcm-ai-playground'
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
      allowEmpty: false
    prune: false