apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hcm-ai-advanced-cluster-management-observability
  namespace: maas-config
spec:
  destination:
    name: in-cluster
  project: default
  source:
    path: operators/advanced-cluster-management/instance/observability
    repoURL: 'https://github.com/app-sre/hcm-ai-playground'
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
      allowEmpty: false
    prune: false
