apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hcm-ai-agent-sandbox
  namespace: maas-config
spec:
  destination:
    name: in-cluster
  project: default
  source:
    path: openshell/agent-sandbox/overlays/default
    repoURL: 'https://github.com/JuanmaBM/hcm-ai-playground'
    targetRevision: feat-openshell-multi-namespace
  syncPolicy:
    automated:
      selfHeal: true
      allowEmpty: false
    prune: false
    syncOptions:
      - CreateNamespace=true
