apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hcm-ai-rhoai
  # namespace: maas-config
spec:
  destination:
    name: in-cluster
  project: default
  source:
    path: operators/rhods-operator/aggregate/overlays/fast-nvidia-gpu/hcmaii01ue1
    repoURL: 'https://github.com/app-sre/hcm-ai-playground'
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
      allowEmpty: false
    prune: false
