apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hcm-ai-servicemesh-operator
  namespace: openshift-gitops
spec:
  destination:
    name: in-cluster
  project: default
  source:
    path: operators/openshift-servicemesh/operator/overlays/stable
    repoURL: 'https://github.com/app-sre/hcm-ai-playground'
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
      allowEmpty: false
    prune: false
