apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: gpt-oss-120b-maas
    security.opendatahub.io/enable-auth: 'true'
    serving.knative.openshift.io/enablePassthrough: 'true'
    serving.kserve.io/deploymentMode: Serverless
    sidecar.istio.io/inject: 'true'
    sidecar.istio.io/rewriteAppHTTPProbers: 'true'
  name: gpt-oss-120b-maas
  namespace: maas
  finalizers:
    - inferenceservice.finalizers
    - odh.inferenceservice.finalizers
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  predictor:
    maxReplicas: 1
    minReplicas: 1
    model:
      args:
        - '--max-model-len'
        - '128000'
      modelFormat:
        name: vLLM
      name: ''
      resources:
        limits:
          nvidia.com/gpu: '4'
        requests:
          cpu: '4'
          memory: 16Gi
          nvidia.com/gpu: '4'
      runtime: gpt-oss-120b-maas
      storage:
        key: models
        path: models-maas/models--redhatai--gpt-oss-120b-FP8-Dynamic
    tolerations:
      - effect: NoSchedule
        key: nvidia-gpu-only
        operator: Exists
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Equal
        value: L40S
    annotations:
      serving.knative.dev/progress-deadline: 30m
