kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: qwen3-32b-maas-view-role
  namespace: maas
  labels:
    opendatahub.io/dashboard: 'true'
rules:
  - verbs:
      - get
    apiGroups:
      - serving.kserve.io
    resources:
      - inferenceservices
    resourceNames:
      - qwen3-32b-maas