apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: token-sync-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: token-sync-role
subjects:
- kind: ServiceAccount
  name: token-sync-sa

