apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hcm-ai-serverless-operator
  namespace: openshift-gitops
spec:
  destination:
    name: in-cluster
  project: default
  source:
    path: serverless-operator/operator/overlays/stable
    repoURL: 'https://github.com/app-sre/hcm-ai-playground'
    targetRevision: main
