apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hcm-ai-nfd
  namespace: openshift-gitops
spec:
  destination:
    name: in-cluster
  project: default
  source:
    path: nfd/aggregate/overlays/default
    repoURL: 'https://github.com/app-sre/hcm-ai-playground'
    targetRevision: main
