apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: oauthclient-argocd-cluster-resources-admin
  namespace: open-cluster-management-observability
rules:
  - apiGroups: 
      - "oauth.openshift.io"
    resources: 
      - "oauthclients"
    verbs: 
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: oauthclient-cluster-resources-admin
  namespace: open-cluster-management-observability
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: oauthclient-argocd-cluster-resources-admin
  namespace: open-cluster-management-observability
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
