apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opendatahub-argocd-cluster-resources-admin
rules:
  - apiGroups: 
      - "opendatahub.io"
      - "datasciencecluster.opendatahub.io"
      - "dscinitialization.opendatahub.io"
      - "dashboard.opendatahub.io"
    resources: 
      - "*"
    verbs: 
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: opendatahub-argocd-cluster-resources-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: opendatahub-argocd-cluster-resources-admin
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops