apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: serviceaccounts-redhat-ods-argocd-cluster-resources-admin
  namespace: redhat-ods-operator
rules:
  - apiGroups: 
      - ""
    resources: 
      - "serviceaccounts"
    verbs: 
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: serviceaccounts-redhat-ods-cluster-resources-admin
  namespace: redhat-ods-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: serviceaccounts-redhat-ods-argocd-cluster-resources-admin
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops