apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tiger-team

resources:
  - namespace.yaml
  - helm-generated.yaml
  - scc-binding.yaml
  - route.yaml
  - policies
  - secrets
  - provider-init-job.yaml

patchesStrategicMerge:
  - gateway-config.yaml

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
