# Valores Helm para tiger-team
# Basados en values-common.yaml pero con overrides específicos

pkiInitJob:
  enabled: false

server:
  disableTls: true
  auth:
    allowUnauthenticatedUsers: true

podSecurityContext:
  fsGroup: null

securityContext:
  runAsUser: null
