---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: 
  - config.secret.yaml
  - grafana-dev-crb.yaml
  - grafana-dev-deploy.yaml
  - grafana-dev-oauthclient.yaml
  - grafana-dev-route.yaml
  - grafana-dev-sa.yaml
  - grafana-dev-svc.yaml
  - grafana-pvc.yaml

configMapGenerator:
- name: config-values
  literals:
    - CLUSTER_URL=supersecret
    - TOKEN_NAME=nothing

replacements:
  - source:
      kind: ConfigMap
      name: config-values
      fieldPath: data.CLUSTER_URL
    targets:
      - select:
          kind: OAuthClient
          name: grafana-proxy-client-dev
        fieldPaths:
          - redirectURIs.0
  - source:
      kind: ConfigMap
      name: config-values
      fieldPath: data.TOKEN_NAME
    targets:
      - select:
          kind: ServiceAccount
          name: grafana-dev
        fieldPaths:
          - imagePullSecrets.0.name
          - metadata.annotations.[openshift.io/internal-registry-pull-secret-ref]
          - secrets.0.name
